ADR-005 Using IAsyncEnumerable to stream large responses
Green-Software-Foundation/carbon-aware-sdk pull request #127
Opened 2022-09-26 21:18 UTC by bderusha

Issue Number: #126 

## Summary
Capturing a relevant design decision within the webAPI to **NOT** use .NET streaming features

## Changes

- ADR-0005 document that the proposal for using `IAsyncEnumerable` to stream at this time is **DENIED**

## Checklist

- [ ] Local Tests Passing?
- [ ] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [ ] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [ ] This is not a breaking change. If it is, please describe it below.

## Are there API Changes? NO

## Is this a breaking change? NO

## Anything else?
Other comments, collaborators, etc.
This PR Closes Issue #126

2022-10-19 21:20 UTC, vaughanknight requested changes
@bderusha - just going through this one which has been delayed due to the 1.0 release.  Logic makes sense and we do need a method to handle large responses.  

Question - Did you mean to propose it with "denied" status?  I think this is something we should definitely look at adding but wanted to understand if there had been any further thinking (or implementation) on this.

2022-10-20 20:44 UTC, bderusha commented
> @bderusha - just going through this one which has been delayed due to the 1.0 release. Logic makes sense and we do need a method to handle large responses.
> 
> Question - Did you mean to propose it with "denied" status? I think this is something we should definitely look at adding but wanted to understand if there had been any further thinking (or implementation) on this.

@vaughanknight This is purposefully submitted as `denied` because we investigated and attempted to implement it.  Unfortunately, it is incompatible with the current error handling flow that the API expects.  For example, right now we throw and catch validation errors to surface useful messages to the user.  With streaming those are managed differently and the stream simply breaks with an unstructured 500 error.

We wanted to capture the reasons why we wanted to explore it, and the reasons why we ultimately decided to not pursue it.  This way other devs don't duplicate the effort unless and underlying reason changes (EG better framework support for intercepting streaming errors, or a different error handling design in the API)

Sorry, we should have provided more context here, because it is a bit weird. Feedback welcome for how to make that message clearer to future readers.

2022-10-25 07:24 UTC, vaughanknight commented
Happy to accept, we just discussed it and I only looked at it briefly and was confused when I first saw it.  The problem I had is the summary is to NOT do something, then the ADR is denied, which means NOT NOT do something, which means do it, where as the ADR itself is to use .NET streaming features (i.e. IAsyncEnumerable) which is what is being denied. :D

2022-11-02 18:28 UTC, bderusha commented
@Willmish @vaughanknight updated this to be `Proposed` so it can merge and be discussed through the normal process.

2022-11-03 09:32 UTC, Willmish approved these changes
LGTM, happy to merge in to be reviewed by GSF

2022-11-15 08:06 UTC, merged