164/update data source config schema
Green-Software-Foundation/carbon-aware-sdk pull request #190
Opened 2022-11-07 22:03 UTC by pritipath

Issue Number: [174](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/172)

DEPENDENT PR
Warning
This PR depends on commits in other PRs
DO NOT merge this PR until https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/158 https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/157 https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/187 and https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/188 are merged and this branch is updated against the latest dev branch

Use [THIS LINK](https://github.com/microsoft/carbon-aware-sdk/commit/7a056578d757806816ddbd1d4da813e66588a5b2#diff-6a5f9ee76b11fddaec8b0340267b56ffa844c370a79cddd41ba50b8457a55875) to review only the code for this PR and hide the dependent commits

## Summary
Provides the ability to configure data source interfaces with a different data source implementation.   

## Changes

- List of comprehensive changes

## Checklist

- [ ] Local Tests Passing?
- [ ] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [ ] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [ ] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?
If yes, what are the expected API Changes? Please link to an API-Comparison workflow with the API Diff.

## Is this a breaking change? Yes
If yes, what workflow does this break? 
Application startup will fail if data source configuration does not represent the desired schema 

## Anything else?
Other comments, collaborators, etc.
> Please follow [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link Pull Requests to Issues via keywords

This PR Closes #<issue_number>

2022-11-14 21:20 UTC, JenMadiedo approved these changes
Lot's of work here, but really cleans up how the data sources are configured, thanks!

2022-11-16 17:47 UTC, JenMadiedo commented on docs/architecture/aggregators.md
>  The `CarbonAwareParameters` class allows the user to pass in a unique parameter instance to the public `CarbonAwareAggregator` methods with the specific parameters needed by that call.
Missed a reference to `CarbonAwareAggregator` here

2022-11-16 17:49 UTC, JenMadiedo commented on docs/architecture/data-sources.md
> -Currently there is one data source interface defined -  `ICarbonIntensityDataSource` - which is the interface for all data sources that provide carbon intensity data. A new data source interface shou
the second part of the sentence doesn't quite make sense anymore. Maybe something along the lines of " - which cover data sources that provide carbon intensity data" or something like that

2022-11-16 17:50 UTC, JenMadiedo commented on docs/architecture/overview.md
>  For example, the `Carbon Intensity Aggregator` handles requests for various carbon emissions information. It can calculate the average carbon emissions over a time period, or the best carbon emission
Another missed reference to the `Carbon Intensity Aggregator`. This whole paragraph might need a quick rewriting

2022-11-18 18:29 UTC, esgraham requested changes
Please update the filename in the configuration.md file.  The other comments are formatting suggestions.

2022-11-18 18:29 UTC, esgraham commented on docs/configuration.md
> +        "DataFileLocation": "test-data.json"
The file name needs to be changed to test-data-azure-emissions.json here and in the rest of the document.

2022-11-21 16:31 UTC, pritipath commented on src/CarbonAware.WebApi/src/appsettings.Development.json.template
>  //copy this file as "appsettings.Development.json",  remove this comment and update the settings below accordingly
Updated the appsettings.template in CLI to use the right config schema. 
We dont anticipate major configuration schema changes any time soon, so for now we think it is ok to have 2 copies of the template file.

2022-11-21 21:31 UTC, esgraham approved these changes

2022-11-28 18:57 UTC, juzuluag approved these changes

2022-11-30 01:58 UTC, pritipath commented
> Currently assuming this one is **not** ready for review from the GSF - let me know if that's incorrect.

I believe all the comments were addressed, so this is ready for GSF review. @gfmatthews could you please review again to see if this looks good to you?

2022-11-30 19:26 UTC, gfmatthews approved these changes
New changes look good! Thank you!

2022-11-30 19:26 UTC, gfmatthews commented
@vaughanknight - this one is now ready for review

2022-12-13 07:32 UTC, vaughanknight approved these changes
This looks great.  Big thank you to the team.

2022-12-13 07:35 UTC, merged