SDK Access Boundaires
Green-Software-Foundation/carbon-aware-sdk pull request #256
Opened 2023-01-20 19:04 UTC by JenMadiedo

Issue Number: #255 

# DEPENDENT PR
> **Warning**
> This PR depends on commits in other PRs
> **DO NOT** merge this PR until https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/253 and https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/245 are merged and this branch is updated against the latest `dev` branch
## Use [THIS LINK](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/217/files/0fc025541e4eac341615ed2f6a4767d5aef588bd..82cb16e3802537d861d37889149e32bf227c8566) to review only the code for this PR and hide the dependent commits

## Summary
Make most non-client facing classes internal. Give access to classes that need internal models. This PR will wait for CLI to move to use Carbon Aware Library as well.

## Changes

- Make most models, interfaces, and classes internal
- Use `InternalsVisibleTo` tag in .csproj files to selectively give access to projects that may need to see certain internals

## Checklist

- [X] Local Tests Passing?
- [X] CICD and Pipeline Tests Passing?
- [X] Added any new Tests?
- [ ] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [ ] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?
If yes, what are the expected API Changes? Please link to an API-Comparison workflow with the API Diff.

## Is this a breaking change?
If yes, what workflow does this break? 

## Anything else?
Other comments, collaborators, etc.
> Please follow [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link Pull Requests to Issues via keywords

This PR Closes #<issue_number>

2023-01-27 18:01 UTC, gfmatthews requested changes
This is a big PR and it's going to really help the maintainability of this repo over the long term! Nice work! A couple questions and comments in line.

Additionally a question - have we done some sanity checking to make sure that the WebAPI and other known endpoints continue to function correctly? We have some customers out there using this code and I'd want to do a double-check that we aren't introducing any known regressions with this change (especially given the scope)

2023-01-30 15:39 UTC, juzuluag reviewed
Thanks for doing this 👍 . Just a few comments to consider.

2023-01-30 15:39 UTC, juzuluag commented on src/CarbonAware.DataSources/CarbonAware.DataSources.Json/src/CarbonAware.DataSources.Json.csproj
> +		<InternalsVisibleTo Include="CarbonAware.DataSources.Json.Tests" />
nit: Indentation

2023-01-30 15:39 UTC, juzuluag commented on src/CarbonAware/src/CarbonAware.csproj
> +	<InternalsVisibleTo Include="CarbonAware.CLI.IntegrationTests"/>
nit: indentation

2023-01-30 15:49 UTC, JenMadiedo commented on src/CarbonAware.Aggregators/test/CarbonAwareParametersTests.cs
> +class CarbonAwareParametersTests
Making these default let us also make all the test bases and types internal. It's just for tests but also still keeps the circle small

2023-01-30 17:08 UTC, JenMadiedo commented on src/CarbonAware.Aggregators/src/Configuration/ServiceCollectionExtensions.cs
> +internal static class ServiceCollectionExtensions
Fixed, thanks for the catch

2023-01-30 17:08 UTC, JenMadiedo commented on src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/Configuration/ServiceCollectionExtensions.cs
> +using CarbonAware.Interfaces;
Fixed, thanks for the catch

2023-01-30 17:08 UTC, JenMadiedo commented on src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/WattTimeDataSource.cs
> +using CarbonAware.DataSources.WattTime.Client;
Fixed, thanks for the catch

2023-01-30 17:29 UTC, JenMadiedo commented on src/CarbonAware.WebApi/src/Program.cs
> +bool successfulServices = true;
I agree, I would take this comment to https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/245 as that's from that PR's commit. This PR inherits from that one (and the one removing the aggregator from the library) so you need to individually select the access boundary commits or use the link in the summary

2023-02-08 20:17 UTC, gfmatthews approved these changes
Thanks for the changes! Looks great!

2023-02-09 19:29 UTC, juzuluag approved these changes
Great 👍

2023-02-21 15:07 UTC, JenMadiedo commented
@vaughanknight this is ready for review

2023-03-14 07:27 UTC, vaughanknight approved these changes
LGTM.  Big coss sweeping change with a lot of effort in it.  Really appreciate the contribution.

2023-03-14 07:27 UTC, merged