ADR for removing Aggregator layer
Green-Software-Foundation/carbon-aware-sdk pull request #275
Opened 2023-02-02 15:03 UTC by pritipath

Issue Number: (Link to Github Issue or Azure Dev Ops Task/Story)

## Summary
With the addition of the GSF library, aggregator layer is an extra overhead in the architecture. The proposal is to remove the Aggregator layer and migrate the data manipulation logic from aggregators to the handlers present in the GSF library.

## Changes

ADR for removing Aggregator layer

## Checklist

- [ ] Local Tests Passing?
- [ ] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [ ] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [ ] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?
If yes, what are the expected API Changes? Please link to an API-Comparison workflow with the API Diff.

## Is this a breaking change?
If yes, what workflow does this break? 

## Anything else?
Other comments, collaborators, etc.
> Please follow [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link Pull Requests to Issues via keywords

This PR Closes #<issue_number>

2023-02-06 15:13 UTC, juzuluag requested changes
Overall looks good. Just a few suggested changes 👍

2023-02-06 15:13 UTC, juzuluag commented on docs/architecture/decisions/0013-remove-aggregator-layer.md
> +With the inclusion of these handlers, the Aggregator layer has now become superfluos. It is an extra pass through layer that contains business logic for data manipulation.
```suggestion
With the inclusion of these handlers, the Aggregator layer has now become obsolete. It is has been replaced by the handlers, which are more aligned with the carbon intensity feature.
```

2023-02-06 15:13 UTC, juzuluag commented on docs/architecture/decisions/0013-remove-aggregator-layer.md
> +- High maintainability since there is less code to maintain
```suggestion
- Less code to maintain.
```

2023-02-06 15:13 UTC, juzuluag commented on docs/architecture/decisions/0013-remove-aggregator-layer.md
> +
```suggestion
- Clear separation of concerns between different layers
```

2023-02-06 16:02 UTC, JenMadiedo approved these changes
Looks good to me. Would it be worth adding some labels in the swimlane to further specify what the layers look like now (Consumers tier are WebAPI, CLI, Library through nuget package etc..), Business layer is the library etc.

2023-02-07 14:30 UTC, juzuluag approved these changes
👍

2023-02-08 16:18 UTC, Kpopovs1 approved these changes

2023-02-08 20:04 UTC, gfmatthews approved these changes
Great job on this!

2023-02-14 00:36 UTC, vaughanknight approved these changes
This looks good, and I assume we will be looking to approve.  Will confirm after today's GSF meeting.

2023-02-14 00:37 UTC, merged