Shorten stale issues by 2 months and stale label to 'stale'
Green-Software-Foundation/carbon-aware-sdk pull request #324
Opened 2023-03-21 14:20 UTC by danuw

Issues to be stale from 120 days of no activity
Label to change to stale and stale-pr to be more explicit

# Pull Request

Issue Number: [(Link to Github Issue or Azure Dev Ops Task/Story)](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/318)

## Summary

Shorten stale issues by 2 months and stale label to 'stale'

## Changes

- Issues to be stale from 120 days of no activity
- Label to change to stale and stale-pr to be more explicit

## Checklist

- [ ] Local Tests Passing?
- [ ] CICD and Pipeline Tests Passing?
- [ ] Documentation Updates Made?
- [X] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?

No

## Is this a breaking change?

No

## Anything else?

Other comments, collaborators, etc.

> Please follow
> [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
> to link Pull Requests to Issues via keywords

This PR is related to [(Link to Github Issue or Azure Dev Ops Task/Story)](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/318)

2023-03-21 14:29 UTC, danuw commented
Updated as discussed in https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/323
I have also renamed no-issue-activity to stale. (and no-pr-activity to stale-pr)

2023-03-23 15:11 UTC, Willmish requested changes
Can we rename the stale label to be the same for both issues and PRs? (Just `stale`?) They are sorted in seperate tab on GH either way, so no need to have different ones, but both `stale` and `stale-pr` will be visible in the PR tab which might cause some confusion.

2023-03-24 13:13 UTC, danuw commented
Done

2023-03-24 13:20 UTC, Willmish approved these changes
LGTM, thanks!

2023-03-24 13:20 UTC, merged