Upgrade to .NET 8.0
Green-Software-Foundation/carbon-aware-sdk pull request #404
Opened 2023-10-16 05:42 UTC by tiwatsuka

# Pull Request

Issue Number:  #401 

## Summary

Upgrade .NET version from 6.0 to 8.0.

## Changes

- change value of `<TargetFramework>` in each `.csproj` file
- change base images of containers for development and building
- update .NET version contained  in comments, documents, and settings

## Checklist

- [x] Local Tests Passing?
- [ ] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [x] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [x] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?

No.

## Is this a breaking change?

No.

This PR Closes #401

2023-10-30 13:59 UTC, bderusha approved these changes
These changes look reasonable. If the tests all pass :shipit:

2023-11-21 08:54 UTC, Willmish commented
@tiwatsuka highlighted https://techcommunity.microsoft.com/t5/apps-on-azure-blog/net-on-azure-functions-august-2023-roadmap-update/ba-p/3910098 :
- Current Sample Azure Functions uses In process model rather than Isolated worker model 
![image](https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/26546660/8015211d-8bc6-4297-b132-05af0199545d)

2023-11-21 08:56 UTC, Sophietn commented
This is blocked until we update Sample Azure Functions from In process model to Isolated worker model - this will be done in a new issue

2023-11-28 08:28 UTC, Willmish commented
To pass https://github.com/Green-Software-Foundation/carbon-aware-sdk/actions/runs/6879323122/job/18711361618?pr=404 , this requires a manual check, with proof of  api-comparison passing (this is currently trying to compare to non-existing previous dotnet8 swagger definition)

2024-01-31 09:21 UTC, YaSuenag requested changes
Please update [containerization.md](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/c0e56baa02574a47b5af1e9d7c9f88dada0f62f8/docs/containerization.md#run-webapi-image) because it mentions exporsed port number of WebAPI. It should be `8080`.

https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port

2024-02-13 04:39 UTC, YaSuenag commented on helm-chart/templates/deployment.yaml
You've changed `containerPort` which cannot be modified via values.yaml, so we have to publish new chart. Could you bump up chart version like this?

https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/449/commits/98c45436744ef04d1d9e8b652ae7de5ec4a1b759

Note that CASDK maintainer should kick [5-publish-helm-chart.yaml](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/.github/workflows/5-publish-helm-chart.yaml) publish after merging.

2024-02-13 04:40 UTC, YaSuenag commented on helm-chart/templates/deployment.yaml
I think `1.1.1` is a good version for this.

2024-02-18 01:56 UTC, YaSuenag commented on helm-chart/templates/deployment.yaml
I reconsidered that we have to release new chart after `vNext` because the chart includes application version (it is equivalent to the tag of container image).

So we can bump up chart version in another PR after `vNext`.

2024-02-18 01:57 UTC, YaSuenag approved these changes
LGTM

Thanks for your work!

2024-02-18 01:57 UTC, YaSuenag commented
@vaughanknight @danuw I agree this PR.

2024-02-27 14:05 UTC, tiwatsuka commented
@danuw I've just resolved documentation conflicts. 
The workflows are not executed because they runs only for PR to `main` or `dev`. Could you execute them manually?

2024-02-28 01:18 UTC, YaSuenag commented
I think we can add `vnext/dotnet8-upgrade` to `.on.pull_request.branches` in `1-pr.yaml` in this branch temporally to run PR tests. Maybe it can run on draft PR, so you can move this to draft PR under PR testing, and move to PR again after removing this branch from `1-pr.yaml` when all tests has been passed. Does it make sence?

2024-02-28 14:46 UTC, tiwatsuka commented
All checks have passed except `api-comparison`. 
https://github.com/Green-Software-Foundation/carbon-aware-sdk/actions/runs/8081752762

`api-comparison` cannot be checked this PR automatically as mentioned before.
https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/404#issuecomment-1829326957

2024-02-28 14:55 UTC, YaSuenag commented
It's good news!

@vaughanknight @danuw Can you merge this to vnext/dotnet8-upgrade branch? #422 relies on this PR - it needs to be rebase after this PR.

2024-03-05 08:19 UTC, vaughanknight reviewed
Looks good as discussed on the call, and all conflicts resolved.  Thanks all!

2024-03-05 08:20 UTC, merged